name: Deploy website to Azure

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Build website 
        run: |
          yarn install
          CI="" yarn run build

      - name: Deploy to Azure
        uses: TravisSpomer/deploy-to-azure-storage@v1.4.0
        with:
          source-path: build
          sas-url: ${{ secrets.DEPLOY_SAS_URL }}
          run: echo ${{ secrets.DEPLOY_SAS_URL}}

