name: Deploy website to Azure

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Build website
        run: |
          yarn install
          CI="" yarn run build

      - name: Deploy to Azure
        uses: TravisSpomer/deploy-to-azure-storage@v1.4.0
        with:
          source-path: build
          sas-url: "https://racuistorage.blob.core.windows.net/$web?sp=racwdl&st=2022-09-14T07:38:40Z&se=2024-09-14T15:38:40Z&spr=https&sv=2021-06-08&sr=c&sig=3xp82oy2Kp8XwbUgLOmitSi9tdmlhpyPIe7GgHDjcg4%3D"
